format_version: 10
pipelines:
  ServiceB:
    group: data-gen
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c5536fd:
        git: https://github.com/santoshbachar/skynet
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - compile:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          compileJob:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '12'
                - '20'
                command: ./genrandom.sh
                run_if: passed
    - unit-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '2'
                - '12'
                command: ./genrandom.sh
                run_if: passed
    - package:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          genpackage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '2'
                - '12'
                command: ./genrandom.sh
                run_if: passed